### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by beatelite** [Ascarbek/suggestbox#1]
Was comparing Multiselects and ran across yours. :+1: 

Could you provide a working example of the following that you mentioned in the readme?
`"Maybe a picture and two lines of data with gray labels ahead. The picture can be at left side or right side or both or mixed depending on odd/even row index. "`

Also, would be great to see plnkr examples of these as it would really help us with implementation. 

Great job on this overall. 

EDIT: for specificity, these guys did a great job with their example: http://plnkr.co/edit/juqoNOt1z1Gb349XabQ2?p=preview

**Comment by Ascarbek** [comment]
Hello!
thank you for your feedback!
I agree with you, there are not enough examples to cover all features. 
I'm planning to work on that next couple days.
I'll add a lot of examples and the one you are asking for will be among the first.

**Comment by beatelite** [comment]
Awesome, thank you! It's a great concept and seems to be well thought out from a UX perspective.

**Comment by beatelite** [comment]
Hey my friend, any luck on the plnkr examples? I'd love to refactor one I'm currently using with yours but want to make sure I understand how each example works.

**Comment by Ascarbek** [comment]
Hello!

I'm sorry for late answer. Was very busy with my job and all the New Year.

I've submitted some bugfixes and changed the DEMO page:
http://ascarbek.github.io/suggestbox

Now it has examples with code and JSFiddle links (plnkr alternative). Have fun!
