### ISSUE TITLE
You're not on NPM

### ISSUE THREAD

**Issue by beatelite** [Ascarbek/suggestbox#2]
Your docs said you could install via npm but I ran into an error. I checked the site and you don't show up. 

https://www.npmjs.com/search?q=SuggestBox

What am I missing?

**Comment by Ascarbek** [comment]
well, it's not an npm package. Sorry if docs are misleading.
you should run '''npm install''', if you cloned this repo, using  '''git clone'''

I recommend you to use bower

**Comment by Ascarbek** [comment]
If you have bower then you should use:
bower install angular-suggestbox

If not, you can just clone the repo like:
git clone https://github.com/Ascarbek/suggestbox

or download as zip, using github's special button for that.

In releases I usually include _dist_ folder where you can find all files you need to use.
