### ISSUE TITLE
Can't get example basic to work

### ISSUE THREAD

**Issue by beatelite** [Ascarbek/suggestbox#3]
I set up a directive following your github advice and loaded all the scripts. 

``` angular
    .module('app', ['azSuggestBox'])
    .directive('suggestboxDirective', [function(){
        return {
            restrict: 'E',
            scope: {
                listItems: '=',
                selectedItems: '=',
                onChange: '&'
            },  
            template: '<input class="tagsinput custom-tag-input" type="text" '+
                'sb-list="listItems" ' +
                'sb-model="selectedItems" ' +
                'sb-on-selection-change="onChange()" ui-jq="tagsinput">'+
                    '<Here goes the layout. />'+
                '</>'
        };
    }]);
```

 I'm using the 'controller as' method of binding the allCampaigns (an array of data) to the scope.

I used the directive in my html and placed the bound data in the listItems attribute. 

```
<suggestbox-directive listItems="articlesEditCtrl.allCampaigns" selectedItems="" onChange=""></suggestbox-directive>
```

The tag input works but I get nothing back from the listItems. No errors, no data, nothing. I know the data is on the scope. 

What  am I missing?

**Comment by Ascarbek** [comment]
I've changed the basic example, now it should work, but you better use the one that is on the demo page: http://ascarbek.github.io/suggestbox

**Comment by beatelite** [comment]
fantastic. I'll check them out. Thanks for the help!
