### ISSUE TITLE
Problem when compiling

### ISSUE THREAD

**Issue by Jisay** [Ascarbek/suggestbox#4]
First thanks for the components. It's really cool !

My problem is the following. When I try to use az-suggest-box directive and I doesn't set a param with two-way data-binding attributes, I get the following error : 

Error: [$compile:nonassign] Expression 'undefined' used with directive 'azSuggestBox' is non-assignable!

When I set all params with two way data binding, it works. Why don't you make optional binding (except for sb-list) ?

Can you set optional data binding in your directives ? It should look like : 

```
scope : { 
     ... , 
     model: ?'=sbModel',
     ... 
}
```

I'm using angular 1.3.20.

Thanks in advance,

Jisay

**Comment by Ascarbek** [comment]
Hi!

at first couldn't repeat the error you are getting, then I realized that I was using older version of angular. After updating I was getting the same error.

So I've set all attributes as optional, except sb-list (it's available with v0.3.0)
